#!/usr/bin/env bash

packages=( helpers )

test () {
    for package in ${packages[*]}
    do
        cd spec/${package}
        go test -v
        cd ../..
    done
}

cover () {
    for package in ${packages[*]}
    do
        cd spec/${package}
        go test -v -coverpkg github.com/grsmv/clio/${package} -cover -coverprofile=cover.out
        go tool cover -html=cover.out
        rm cover.out
        cd ../..
    done
}

case $1 in
    cover) cover ;;
    *)     test  ;;
esac
